name: Check Markdown links

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npx markdown-link-check . --no-config
    - uses: gaurav-nelson/github-action-markdown-link-check@v1