name: Lint YAML files

on:
  push:

jobs:
    lint-yaml:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: yaml-lint
              uses: ibiqlik/action-yamllint@v3
