name: Detect secrets leaks
on:
  workflow_call:
  push:
    branches:
      - '**'

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout trufflehug_config.yaml
        uses: actions/checkout@v4
        with:
          repository: ai-cfia/github-workflows
          path: github-workflows
          ref: 172-make-sure-no-api-key-is-inside-our-repos
          sparse-checkout: |
            trufflehog_config.yaml
          sparse-checkout-cone-mode: false
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --config=github-workflows/trufflehog_config.yaml --results=verified,unknown
