name: Detect secrets leaks
on:
  workflow_call:
  push:
    branches:
      - '**'

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create TruffleHog configuration file (detect ailab-* prefix)
        run: |
          cat > config.yaml <<EOL
          regexes:
            - name: ailab_prefix_detector
              regex: 'ailab-.*'
              description: Detects strings with 'ailab-' prefix
              tags:
                - "ailab"
          detectors:
            - pattern: 'ailab-.*'
              part: 'token'
              name: 'ailab'
          EOL
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --config=config.yaml --results=verified,unknown
