name: Check Markdown links

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Create empty config file
      run: echo '{}' > empty-config.json

    - name: Checkout code
      uses: actions/checkout@master

    - name: Validating links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: './empty-config.json'