name: Reusable Build and Deploy to GitHub Pages

on:
    workflow_call:
      secrets:
        ENV:
          required: false

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

    - name: Install Dependencies
      run: npm install
      working-directory: ${{ env.WORKING_DIR }}

    - name: Build
      run: npm run build
      working-directory: ${{ env.WORKING_DIR }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.PUBLISH_DIR }}
        publish_branch: ${{ env.PUBLISH_BRANCH }}
