---
name: Reusable Docker container deployment to Azure

on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.ACR_SERVER }}/${{ inputs.container-name }}"
          IMAGE="${IMAGE}:${{ inputs.tag }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ github.event.repository.name }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: >-
            ${{ secrets.ACR_SERVER }}/${{ inputs.container-name }}:
            ${{ inputs.tag }}
