name: Ansible Workflow

on:
  workflow_call:
    inputs:
      ansible-lint-config:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ inputs.python-version }}'

      - name: Install ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Debug
        run: ls -la ${{ github.workspace }}

      - name: Run ansible-lint
        run: ansible-lint -c ${{ github.workspace }}/${{ inputs.ansible-lint-config }} ${{ github.workspace }}
