name: Detect secrets leaks
on:
  workflow_call:
  push:

jobs:
  trufflehog:
    runs-on: on-prem-gh-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch trufflehog_config.yaml from workflows repo
        uses: actions/checkout@v4
        with:
          repository: ai-cfia/github-workflows
          path: github-workflows
          ref: 172-make-sure-no-api-key-is-inside-our-repos
          sparse-checkout: |
            trufflehog_config.yaml
          sparse-checkout-cone-mode: false

      - name: Install TruffleHog binary (without Docker)
        run: |
          mkdir -p $HOME/bin
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run TruffleHog Git Scan
        run: |
          trufflehog git https://github.com/${{ github.repository }}.git \
            --branch ${{ github.ref_name }} \
            --config=github-workflows/trufflehog_config.yaml \
            --results=verified,unknown \
            --fail
