---
name: Reusable lint and test workflow for Node (React) projects

on:
    workflow_call:

jobs:
    lint-test:
        runs-on: ubuntu-latest
        environment: experimental
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: install npm
              run: npm install
            - name: install dependencies
              run: npm install
            - name: Run ESLint
              run: npm run lint
            - name: Run tests
              run: npm test
