name: Validate file presence

on:
  workflow_call:
    inputs:
      files:
        required: true
        type: string

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Check for file
      run: |
        IFS=',' read -ra FILE_ARRAY <<< "${{ github.event.inputs.files }}"
        for file in "${FILE_ARRAY[@]}"; do
          if [[ -f "$file" ]]; then
            echo "$file exists."
          else
            echo "Error: $file does not exist!" >&2
            exit 1
          fi
        done
      shell: bash
