name: Ansible Workflow

on:
  workflow_call:
    inputs:
      ansible-lint-file:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible and ansible-lint
        run: sudo apt install -y ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint -c ${{ github.event.inputs.ansible-lint-file }}
