name: Reusable lint and test workflow for Python projects

on:
  workflow_call:
    inputs:
      skip-coverage:
        required: false
        type: string
        default: 'false'

permissions:
  actions: read
  pull-requests: write

jobs:
  lint-test:
    runs-on: gh-runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.1.0
          if [ -f requirements.txt ]; then \
            pip install -r requirements.txt; \
          fi
          pip install pytest pytest-cov # for coverage

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py311 .
          # default set of ruff rules with GitHub Annotations
          ruff --output-format=github --target-version=py311 .

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Test with pytest
        run: |
          python -m pytest

      - name: Run tests with coverage (coverage must be at least 80% to pass)
        if: inputs.skip-coverage != 'true'
        run: |
          python -m pytest --cov=. --cov-fail-under=80
