name: Python package

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py311 .
        # default set of ruff rules with GitHub Annotations
        ruff --format=github --target-version=py311 .
    # - name: Test with pytest
    #   run: |
    #     pytest
    #   env:
    #     LOUIS_DSN: ${{ secrets.LOUIS_DSN }}
    #     LOUIS_SCHEMA: ${{ secrets.LOUIS_SCHEMA }}
    - name: Test with unittest
      run: |
        python -m unittest discover -s tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LOUIS_DSN: ${{ secrets.LOUIS_DSN }}
        LOUIS_SCHEMA: ${{ secrets.LOUIS_SCHEMA }}
        AZURE_OPENAI_SERVICE: ${{ secrets.AZURE_OPENAI_SERVICE }}