name: Verify Committer Email
on:
  workflow_call:
  push:

jobs:
  check-commit-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dguo/check-author-and-committer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          committer-email-regex: '@(?:[a-zA-Z0-9-]+\.)?gc\.ca$|^noreply@github\.com$'
          custom-error-message: "Commits must be signed with an email address ending in .gc.ca. Please configure your email address correctly."
