name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    workflow_call:

permissions:
    checks: read
    contents: read
    pull-requests: write

jobs:
  Deploy-Preview-and-Comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - run: sleep 30

      - name: Comment on PR
        uses: JoseThen/comment-pr@v1.2.0
        with:
            comment: "Your deployment is like at https://ai-cfia-website.vercel.app/"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
