---
name: "Pull request Labeler"

on:
  workflow_call:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Labelling pull request
        uses: actions/labeler@v5
        with:
          configuration-path: 'labeler.yml'
