name: Create Release

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Parse version from pyproject.toml
        id: parse_version
        run: |
          version=$(grep -Po '(?<=^version = ")[^"]*' pyproject.toml)
          echo "version=$version" >> $GITHUB_ENV

      - name: Tag the version and push
        run: |
          git tag -a v${{ env.version }} -m "Release ${{ env.version }}"
          git push origin v${{ env.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.version }}"
          name: "${{ github.repository }} v${{ env.version }}"
          body: "Release version ${{ env.version }} for ${{ github.repository }}."
          allowUpdates: true
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
