name: Check Markdown links

on:
  workflow_call:
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Validating links
      uses: gaurav-nelson/github-action-markdown-link-check@v1

    - name: Verify line 80 wrap
      uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        config: .markdownlint.json
