name: Check Markdown conformance to AI Lab standards

on:
  workflow_call:
    inputs:
      md-link-config-file-path:
        required: false
        type: string
      md-lint-config-file-path:
        required: false
        type: string
  push:

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validating links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '${{ inputs.md-link-config-file-path }}'

      - name: Checkout reusable workflows repository if custom config not provided
        if: inputs.md-lint-config-file-path == ''
        uses: actions/checkout@v4
        with:
          repository: ai-cfia/github-workflows
          path: github-workflows
          ref: main
          sparse-checkout: |
            .markdownlint.json
          sparse-checkout-cone-mode: false

      - name: Determine markdown lint config file
        id: lintconfig
        run: |
          if [ -z "${{ inputs.md-lint-config-file-path }}" ]; then
            echo "::set-output name=config_path::github-workflows/.markdownlint.json"
          else
            echo "::set-output name=config_path::${{ github.workspace }}/${{ inputs.md-lint-config-file-path }}"
          fi

      - name: Run markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v14
        # Run step even if previous steps fail.
        if: always()
        with:
          globs: '**/*.md'
          config: ${{ steps.lintconfig.outputs.config_path }}
