name: Reusable Build and Deploy to GitHub Pages

on:
    workflow_call:
      inputs:
        node-version:
          required: true
          type: string
        publish-dir:
          required: true
          type: string
        cache-dependency-path:
          required: true
          type: string
        working-dir:
          required: false
          type: string
          default: '.'
        publish-branch:
          required: false
          type: string
          default: 'gh-pages'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.working-dir }}

    - name: Set ENV
      run: |
        echo "${{ secrets.ENV }}" >> $GITHUB_ENV

    - name: Install Dependencies
      run: npm install
      working-directory: ${{ inputs.working-dir }}

    - name: Build
      run: npm run build
      working-directory: ${{ inputs.working-dir }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.publish-dir }}
        publish_branch: ${{ inputs.publish-branch }}
