name: Reusable Build and Deploy to GitHub Pages

on:
    workflow_call:
      inputs:
        env_file:
          required: false
          type: string

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ inputs.env_file }}

    steps:
      - name: test
        run: echo ${{ env.ENV }}
    # - name: Checkout Repository
    #   uses: actions/checkout@v3

    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}
    #     cache: npm
    #     cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

    # - name: Install Dependencies
    #   run: npm install
    #   working-directory: ${{ env.WORKING_DIR }}

    # - name: Build
    #   run: npm run build
    #   working-directory: ${{ env.WORKING_DIR }}

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ${{ env.PUBLISH_DIR }}
    #     publish_branch: ${{ env.PUBLISH_BRANCH }}
