name: Ansible Workflow

on:
  workflow_call:
    inputs:
      ansible-lint-config:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: '3.9'
      ansible-variable-file:
        required: false
        type: string
        default: ''
      ansible-inventory-file:
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ inputs.python-version }}'

      - name: Install ansible, ansible-lint and ansible-vault
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint ansible-vault

      - name: Create the ansible vault password file
        run: echo -n "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ${{ github.workspace }}/.ansible_vault_password.txt

      - name: Decrypt variables
        if: ${{ inputs.ansible-variable-file != '' }}
        run: ansible-vault decrypt --vault-password-file .ansible_vault_password.txt ${{ github.workspace }}/${{ inputs.ansible-variable-file }}

      - name: Decrypt inventory
        if: ${{ inputs.ansible-inventory-file != '' }}
        run: ansible-vault decrypt --vault-password-file .ansible_vault_password.txt ${{ github.workspace }}/${{ inputs.ansible-inventory-file }}

      - name: Run ansible-lint
        run: ansible-lint -c ${{ github.workspace }}/${{ inputs.ansible-lint-config }} ${{ github.workspace }}
