---
name: "Pull request Labeler"

on:
  workflow_call:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository containing labeler.yml
        uses: actions/checkout@v3
        with:
          repository: ai-cfia/github-workflows
          path: github-workflows

      - name: Labelling pull request
        uses: actions/labeler@v5
        with:
          configuration-path: 'github-workflows/labeler.yml'
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: |
            ${{ github.event.number }}
