---
name: Check SH scripts conformance to AI Lab standards

on:
    workflow_call:
    push:

jobs:
    sh-lint-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Run ShellCheck
              uses: azohra/shell-linter@latest
