name: Reusable lint workflow for Python projects (monorepo)

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."

permissions:
  actions: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.1.0

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py311 .
          # default set of ruff rules with GitHub Annotations
          ruff --output-format=github --target-version=py311 .
